export const items = [
    {
        id:8,
        title: "Hanssen",
        description: "Industrial transmission components",
        tags: ["Custom theme", "WordPress"],
        link: "https://hanssen.mickael-grass.com",
        imageSrc: "./img/projects/hanssen.jpg",
    },
    {
        id:6,
        title: "Dimaco",
        description: "Industrial transmission components",
        tags: ["API", "WordPress"],
        link: "https://dimaco.fr",
        imageSrc: "./img/projects/Dimaco.jpg",
    },
    {
        id:7,
        title: "Fischbach",
        description: "De la nature aux vins d'Alsace",
        tags: ["API", "WordPress"],
        link: "https://fischbach.mickael-grass.com",
        imageSrc: "./img/projects/Fischbach.jpg",
    },
    {
        id:0,
        title: "IRCAD",
        description: "IRCAD, innovation & excellence for surgery",
        tags: ["WordPress", "Custom CRM"],
        link: "https://www.ircad.fr",
        imageSrc: "./img/projects/IRCAD.jpg",
    },
    {
        id:1,
        title: "StravaApp",
        description: "Gathering Strava API to display statistics",
        tags: ["ReactJS", "API"],
        link: "https://strava-api.surge.sh/",
        imageSrc: "./img/projects/StravaAPI.jpg",
    },
    {
        id:2,
        title: "WebSurg",
        description: "Online university of IRCAD, for surgeons",
        tags: ["PHP", "Symfony", "WebDesign"],
        link: "https://www.websurg.com",
        imageSrc: "./img/projects/WebSurg.jpg",
    },
    {
        id:3,
        title: "Eurospine",
        description: "Book your event and register online",
        tags: ["WordPress", "CustomTheme", "WebDesign"],
        link: "https://registration.ircad.fr",
        imageSrc: "./img/projects/Eurospine.jpg",
    },
    {
        id:4,
        title: "Password Generator",
        description: "Generate a random password with your preferences",
        tags: ["Javascript", "WebDesign"],
        link: "https://password-suggestion.surge.sh",
        imageSrc: "./img/projects/PasswordGenerator.jpg",
    },
    {
        id:5,
        title: "RealTime message",
        description: "Small Discord-like!",
        tags: ["JS vanilla"],
        link: "http://message-app.surge.sh/",
        imageSrc: "./img/projects/RealtimeMessageApp.jpg",
    }
    
]